package com.example.intro2computer;

public class QuestionAnswer {
    public static String question[] = {
            "1. The use of computer to carry out crime related activities is called _____",
            "2. Transistors are special features of which generation of computer classification",
            "3. _____ is the technology used in first generation",
            "4. _____ is the technology for the Third generation of Computer classification is associated",
            "5. What year was vacuum tube invented?",
            "6. Information can be referred to as processed ____",
            "7. One of these does not explain the stage of computer except?",
            "8. The computer program to compute the bernoulli's sequence on the Analytical Engine was written by _____",
            "9. In what year did Blaise Pascal invent the first mechanical calculator? ",
            "10. In 1822 _________ built two enormous engines.",
            "11. All of these are characteristics of Computers except ",
            "12. ______ was invented in 1617 to replace tradition method for counting?",
            "13. A computer is basically defined as a tool or machine used for processing data to give required information.",
            "14. _____ made the most outstanding and important mechanical device",
            "15. _____ is a technology invented in the fourth generation",
            "16. ______ is a technology used in fifth generation and was invented in 1990 to date.",
            "17. The vacuum tube was invented by the British scientists called _____ ",
            "18. ____ is regarded as the first programmable computer",
            "19. The following are methods of data processing except",
            "20. Computer processing speeds are measured in _____",
            "21. Which generation of computers marked the beginning of the use of keyboard for input of data and monitor for output?",
            "22. Which aspect of the CPU controls the activities/ the operations of the Microprocessor",
            "23. Which aspect of the computer memory can be described as volatile? ",
            "24. Operating System is an example of ______",
            "25. Computer storage capabilities can be measured in ____",
            "26. All these are types of computer except one",
            "27. _____ is an example of Digital computer ",
            "28. _____ is an  example of Analogue Computers",
            "29. Which of the following class of digital computers is traditionally the fastest and most expensive?",
            "30. ____- are the largest, fastest and most expensive computers.",
            "31. All of these are components of Computer except",
            "32. ____ is a large and expensive general purpose computer.",
            "33. These are computer with smaller physical size, generate less heat than main frame.",
            "34. Some instances of sector-based computer applications are listed below except___",
            "35. The Electronic Computer was advent into Nigeria during the National Census in what year?",
            "36. ____ is a word processor that is part of the microsoft office suit.",
            "37. ____ is a internet collection of local, regional and International computer networks that are linked together to exchange data or information and distribute processing task.",
            "38. World wide web is universal database collection of information.",
            "39. Web browser or internet browser is referred to a browser is a software application for retrieving, presenting and traversing information resources on the world wide web.",
            "40. Full meaning of HTTP?",
            "41. Full meaning of DHCP",
            "42. All of these are example of search engine except.",
            "43. All of these are example of Graphic Design, visual communication and problem solving through the use of typography, photography and illustration.",
            "44. _____ is a computer program that set out a grid where users can analyze and organize numbers, financial data, and other information.",
            "45. _____ is a computer program that provides visual indicators such as graphical icons, symbols, to users to enable them interact with electronic devices rather than through a command line",
            "46. ________ is a set of instructions and its associated documentations that controls the hardware or tells a computer what to do and how to perform a task.",
            "47. _____  acts as an intermediary between the user of a computer and computer hardware.",
            "48 What's the full meaning of PAN",
            "49. What's the full meaning of VPN?",






    };

    public static String choices[][] ={
            {"Automated Stealing", "Stealing", "Tech-based bugle", "Cybercrime"},
            {"First", "Second", "Third", "Fourth"},
            {"Transistor", "Integrated Circuit ", "Large scale integrated circuit ", "Vacuum tube"},
            {"Vacuum Tube", "Transistors", "Integrated Circuit", "None of the above"},
            {"1995", "1964", "1946", "1990"},
            {"Paper", "Ideas", "Data", "Plastic"},
            {"Output - data - information", "Input - processing - output", "Processing - input - output", "None of the above"},
            {"John Atanasoff", "Grace Hopper", "Charles babbage", "Ada lovelace"},
            {"1942", "1642", "1756", "1655"},
            {"Blaise Pascal", "Gottfried Leibniz", "Charles Babbage ", "Herman hollerith"},
            {"Speed", "Accuracy", "Acceleration", "Reliability"},
            {"Calculator", "Mechanical calculator", "Abacus device", "None of the above"},
            {"True", "False", "", ""},
            {"Herman hollerith", "Blaise pascal", "Charles Babbage", "None of the above"},
            {"Large scale Integrated circuit (1972 - 1987)", "Integrated circuit (1964 - 1972)", "Vacuum tube (1946)", "Transistors (1955 - 1964)"},
            {"Vacuum tube", "Integrated Circuit", "Transistors", "Knowledge based system"},
            {"Alan Turing", "John flaming", "Howard aiken", "Charles Babbage"},
            {"Abacus", "ENIAC", "Colossus", "Analytical Engine"},
            {"Magnetic", "Manual", "Mechanical", "Computerized"},
            {"Kilograms", "Kilohertz", "Kilobytes", "Kilometers"},
            {"First", "Second", "Third", "Fourth"},
            {"ACU", "ALU", "CU", "ATU"},
            {"ROM", "RAM", "Disk", "Tape"},
            {"Application software", "Utility program", "System software", "General software"},
            {"Kilogram", "Kilohertz", "Kilobytes", "Kilometers"},
            {"Analogue computer", "Automated computer", "Digital computer", "Hybrid computer"},
            {"Calculator & Wrist watch", "Thermometers", "Television", "None of the above"},
            {"Thermometer & petrol dispenser", "Robot", "Television", "Radio"},
            {"Mainframe", "Mini Computers", "Micro computers", "Super computers"},
            {"Mainframe", "Mini Computers", "Micro computers", "Super computers"},
            {"Input and output", "Hardware", "Software", "Firmware"},
            {"Mainframe", "Mini Computers", "Micro computers", "Super computers"},
            {"Mini Computer", "Micro Computer", "Super Computer", "None of the above"},
            {"Computer applied in health care device delivery", "Computer applied in Education, Teaching and Learning", "Computer applied in business", "Computer applied in village "},
            {"1955", "1999", "1963", "1946"},
            {"Microsoft word", "Adobe word", "Microsoft PowerPoint", "None of the above"},
            {"Computer", "Adobe word", "Internet", "Protocols"},
            {"True", "False", "", ""},
            {"True", "False", "", ""},
            {"Hyper transfer protocol", "Hypertransfer text protocol", "Hyper text transfer protocol", "None of the above"},
            {"Digital host context protocol", "Digital hypertext configure protocol", "Dynamic Host Configuration Protocol", "Dynamics host Configurations Protocols"},
            {"Wikipedia", "Google", "Facebook", "Ask.com"},
            {"Corel Draw", "Adobe Photoshop", "Adobe illustrator", "Spreadsheet"},
            {"Spreadsheet application", "Graphic application", "Rows and column", "Power point"},
            {"Graphics", "Graphical user interface (GUI)", "Operator", "None of the above"},
            {"Computer software", "Programming Language", "IoT", "Protocol"},
            {"Operating system", "Application system", "Software package", "Windows"},
            {"Protocol area network", "Personal  Area Network", "Personal Automate network", "Pin Area Network"},
            {"Virtual Private Network", "Visual protocol net", "Virtual platform network", "None of the above"}
    };

    public static String correctAnswers[] ={
            "Cybercrime",
            "Second",
            "Vacuum tube",
            "Integrated Circuit",
            "1946",
            "Data",
            "Input - processing - output",
            "Charles babbage",
            "1642",
            "Charles Babbage",
            "Acceleration",
            "Abacus device",
            "True",
            "Herman hollerith",
            "Large scale Integrated circuit (1972 - 1987)",
            "Knowledge based system",
            "Charles Babbage",
            "Analytical Engine",
            "Mechanical",
            "Kilohertz",
            "Fourth",
            "ALU",
            "RAM",
            "System software",
            "Kilobytes",
            "Automated computer",
            "Calculator & Wrist watch",
            "Thermometer & petrol dispenser",
            "Super computers",
            "Super computer",
            "Input and output",
            "Mainframe",
            "Mini computer",
            "Computer applied in village",
            "1963",
            "Microsoft word",
            "Internet",
            "True",
            "True",
            "Hyper text transfer protocol",
            "Dynamic Host Configuration Protocol",
            "Facebook",
            "Spreadsheet",
            "Spreadsheet application",
            "Graphical user interface (GUI)",
            "Computer software",
            "Operating system",
            "Personal  Area Network",
            "Virtual Private Network",
    };
};