package com.example.intro2computer;

public class QuestionAnswer {
    public static String question[] = {
            "The use of computer to carry out crime related activities is called _____",
            "Transistors are special features of which generation of computer classification",
            "_____ is the technology used in first generation",
            "_____ is the technology for the Third generation of Computer classification is associated",
            "What year was vacuum tube invented?",
            "Information can be referred to as processed ____",
            "One of these does not explain the stage of computer except?",
            "The computer program to compute the bernoulli's sequence on the Analytical Engine was written by _____",
            "In what year did Blaise Pascal invent the first mechanical calculator? ",
            "In 1822 _________ built two enormous engines.",
            "All of these are characteristics of Computers except ",
            "______ was invented in 1617 to replace tradition method for counting?",
            "A computer is basically defined as a tool or machine used for processing data to give required information.",
            "_____ made the most outstanding and important mechanical device",
            "_____ is a technology invented in the fourth generation",
            "______ is a technology used in fifth generation and was invented in 1990 to date.",
            "The vacuum tube was invented by the British scientists called _____ ",
            "____ is regarded as the first programmable computer",
            "The following are methods of data processing except",
            "Computer processing speeds are measured in _____",
            "Which generation of computers marked the beginning of the use of keyboard for input of data and monitor for output?",
            "Which aspect of the CPU controls the activities/ the operations of the Microprocessor",
            "Which aspect of the computer memory can be described as volatile? ",
            "Operating System is an example of ______",
            "Computer storage capabilities can be measured in ____",
            "All these are types of computer except one",
            "_____ is an example of Digital computer ",
            "_____ is an  example of Analogue Computers",
            "Which of the following class of digital computers is traditionally the fastest and most expensive?",
            "____- are the largest, fastest and most expensive computers.",
            "All of these are components of Computer except",
            "____ is a large and expensive general purpose computer.",
            "These are computer with smaller physical size, generate less heat than main frame.",
            "Some instances of sector-based computer applications are listed below except___",
            "The Electronic Computer was advent into Nigeria during the National Census in what year?",
            "____ is a word processor that is part of the microsoft office suit.",
            "____ is a internet collection of local, regional and International computer networks that are linked together to exchange data or information and distribute processing task.",
            "World wide web is universal database collection of information.",
            "Web browser or internet browser is referred to a browser is a software application for retrieving, presenting and traversing information resources on the world wide web.",
            "Full meaning of HTTP?",
            "Full meaning of DHCP",
            "All of these are example of search engine except.",
            "All of these are example of Graphic Design, visual communication and problem solving through the use of typography, photography and illustration.",
            "_____ is a computer program that set out a grid where users can analyze and organize numbers, financial data, and other information.",
            "_____ is a computer program that provides visual indicators such as graphical icons, symbols, to users to enable them interact with electronic devices rather than through a command line",
            "________ is a set of instructions and its associated documentations that controls the hardware or tells a computer what to do and how to perform a task.",
            "_____  acts as an intermediary between the user of a computer and computer hardware.",
            "What's the full meaning of PAN",
            "What's the full meaning of VPN?",
            "Which component is considered the brain of the computer",
            "What does RAM stand for?",
            "Which device is used to convert digital signals into analog for transmission??",
            "Which of these is not an input device?",
            "What is the main function of a printer?",
            "Which type of memory is permanent?",
            "Which device is used to store large amounts of data?",
            "What is the full form of SSD?",
            "Which hardware device processes all data and instructions?",
            "BIOS is stored in which type of memory?",
            "What is software?",
            "Which of these is an operating system?",
            "What is the primary purpose of an operating system?",
            "Which of the following is an example of application software?",
            "What is the full form of GUI?",
            "Which type of software translates high-level language into machine language?",
            "What does HTTP stand for?",
            "Which of the following is not a type of system software?",
            "Which of the following is an example of open-source software?",
            "Which software is used for designing and creating web pages?",
            "What is the smallest unit of data in a computer?",
            "Which numbering system is used in computers?",
            "The process of starting a computer is called?",
            "Which of the following is an example of a high-level programming language?",
            "Which of these is not a type of computer?",
            "What does IP in IP address stand for?",
            "Which is the first generation of computers?",
            "Which device connects multiple networks?",
            "The full form of URL is:",
            "What does DNS stand for?",
            "Which of these is an output device",
            "Which of these represents temporary memory?",
            "Which programming language is known as the \"mother of all languages\"",
            "Which of the following is not a storage device?",
            "What does the acronym WAN stand for?",
            "Which type of software is used for calculations and data analysis?",
            "Which programming language is used for Artificial Intelligence?",
            "What is a collection of interconnected computers called?",
            "Which port is commonly used for internet browsing?",
            "The first mechanical computer was called:",
            "What is the primary function of a computer?",
            "What does CPU stand for?",
            "Which device is known as the brain of the computer?",
            "Which of these is an input device?",
            "Which part of the computer is used to store data permanently?",
            "What does RAM stand for??",
            "Which software controls the overall operation of a computer?",
            "What is the function of an output device?",
            "Which of these is an example of system software?",
            "What does GUI stand for?",
            "What is OOPs?"
    };

    public static String choices[][] ={
            {"Automated Stealing", "Stealing", "Tech-based bugle", "Cybercrime"},
            {"First", "Second", "Third", "Fourth"},
            {"Transistor", "Integrated Circuit ", "Large scale integrated circuit ", "Vacuum tube"},
            {"Vacuum Tube", "Transistors", "Integrated Circuit", "None of the above"},
            {"1995", "1964", "1946", "1990"},
            {"Paper", "Ideas", "Data", "Plastic"},
            {"Output - data - information", "Input - processing - output", "Processing - input - output", "None of the above"},
            {"John Atanasoff", "Grace Hopper", "Charles babbage", "Ada lovelace"},
            {"1942", "1642", "1756", "1655"},
            {"Blaise Pascal", "Gottfried Leibniz", "Charles Babbage ", "Herman hollerith"},
            {"Speed", "Accuracy", "Acceleration", "Reliability"},
            {"Calculator", "Mechanical calculator", "Abacus device", "None of the above"},
            {"True", "False", "", ""},
            {"Herman hollerith", "Blaise pascal", "Charles Babbage", "None of the above"},
            {"Large scale Integrated circuit (1972 - 1987)", "Integrated circuit (1964 - 1972)", "Vacuum tube (1946)", "Transistors (1955 - 1964)"},
            {"Vacuum tube", "Integrated Circuit", "Transistors", "Knowledge based system"},
            {"Alan Turing", "John flaming", "Howard aiken", "Charles Babbage"},
            {"Abacus", "ENIAC", "Colossus", "Analytical Engine"},
            {"Magnetic", "Manual", "Mechanical", "Computerized"},
            {"Kilograms", "Kilohertz", "Kilobytes", "Kilometers"},
            {"First", "Second", "Third", "Fourth"},
            {"ACU", "ALU", "CU", "ATU"},
            {"ROM", "RAM", "Disk", "Tape"},
            {"Application software", "Utility program", "System software", "General software"},
            {"Kilogram", "Kilohertz", "Kilobytes", "Kilometers"},
            {"Analogue computer", "Automated computer", "Digital computer", "Hybrid computer"},
            {"Calculator & Wrist watch", "Thermometers", "Television", "None of the above"},
            {"Thermometer & petrol dispenser", "Robot", "Television", "Radio"},
            {"Mainframe", "Mini Computers", "Micro computers", "Super computers"},
            {"Mainframe", "Mini Computers", "Micro computers", "Super computers"},
            {"Input and output", "Hardware", "Software", "Firmware"},
            {"Mainframe", "Mini Computers", "Micro computers", "Super computers"},
            {"Mini Computer", "Micro Computer", "Super Computer", "None of the above"},
            {"Computer applied in health care device delivery", "Computer applied in Education, Teaching and Learning", "Computer applied in business", "Computer applied in village "},
            {"1955", "1999", "1963", "1946"},
            {"Microsoft word", "Adobe word", "Microsoft PowerPoint", "None of the above"},
            {"Computer", "Adobe word", "Internet", "Protocols"},
            {"True", "False", "", ""},
            {"True", "False", "", ""},
            {"Hyper transfer protocol", "Hypertransfer text protocol", "Hyper text transfer protocol", "None of the above"},
            {"Digital host context protocol", "Digital hypertext configure protocol", "Dynamic Host Configuration Protocol", "Dynamics host Configurations Protocols"},
            {"Wikipedia", "Google", "Facebook", "Ask.com"},
            {"Corel Draw", "Adobe Photoshop", "Adobe illustrator", "Spreadsheet"},
            {"Spreadsheet application", "Graphic application", "Rows and column", "Power point"},
            {"Graphics", "Graphical user interface (GUI)", "Operator", "None of the above"},
            {"Computer software", "Programming Language", "IoT", "Protocol"},
            {"Operating system", "Application system", "Software package", "Windows"},
            {"Protocol area network", "Personal  Area Network", "Personal Automate network", "Pin Area Network"},
            {"Virtual Private Network", "Visual protocol net", "Virtual platform network", "None of the above"},
            {"CPU", "RAM", "Hard Disk", "ROM"},
            {"Random Access Memory", "Read Access Memory", "Random Arithmetic Memory", "Rapid Access Memory"},
            {"Router", "Modem", "Switch", "Hub"},
            {"Keyboard", "Mouse", "Monitor", "Scanner"},
            {"Input data", "Process data", "Output data", "Store data"},
            {"RAM", "ROM", "Cache", "Virtual Memory"},
            {"CPU", "Hard Disk Drive (HDD)", "Scanner", "Monitor"},
            {"Super Storage Device", "Solid State Drive", "Secondary Storage Drive", "Storage State Device"},
            {"CPU", "RAM", "Monitor", "Keyboard"},
            {"RAM", "ROM", "Hard Disk", "Cache"},
            {"Physical components of a computer", "Set of instructions to perform tasks", "Storage devices", "Network hardware"},
            {"Microsoft Word", "Google Chrome", "Linux", "Adobe Photoshop"},
            {"Perform calculations", "Manage hardware and software resources", "Display data", "Connect to the internet"},
            {"Windows 10", "Manage hardware and software resources", "Display data", "Connect to the internet"},
            {"General User Interface", "Graphical User Interface", "Global User Interface", "Graphics Utility Interface"},
            {"Compiler", "Operating System", "Utility Software", "Browser"},
            {"Hyperlink Transfer Text Protocol", "Hypertext Transfer Protocol", "Hyper Transfer Text Protocol", "Hyperlink Text Transmission Protocol"},
            {"Operating System", "Device Drivers", "File Manager", "Antivirus"},
            {"Microsoft Word", "Adobe Photoshop", "Linux", "Windows 11"},
            {"Microsoft Excel", "Adobe Dreamweaver", "VLC Media Player", "Norton Antivirus"},
            {"Bit", "Byte", "Kilobyte", "Megabyte"},
            {"Decimal", "Octal", "Binary", "Hexadecimal"},
            {"Debugging", "Booting", "Formatting", "Loading"},
            {"Assembly", "Java", "Machine Code", "Binary Code"},
            {"Microcomputer", "Mainframe", "Supercomputer", "Switch"},
            {"Internet Protocol", "Internal Process", "Internet Provider", "Internal Protocol"},
            {"Vacuum Tubes", "Transistors", "Integrated Circuits", "Microprocessors"},
            {"Router", "Switch", "Hub", "Modem"},
            {"Universal Resource Locator", "Uniform Resource Locator", "Unified Resource Locator", "Universal Route Locator"},
            {"Domain Name System", "Data Network System", "Digital Name Service", "Distributed Name Server"},
            {"Keyboard", "Printer", "Mouse", "Scanner"},
            {"ROM", "RAM", "Hard Disk", "CD-ROM"},
            {"C", "Python", "Java", "Assembly"},
            {"Hard Disk", "RAM", "Scanner", "Flash Drive"},
            {"Wide Area Network", "Wireless Access Network", "Web Area Network", "Wired Access Network"},
            {"Database Software", "Spreadsheet Software", "Graphics Software", "Utility Software"},
            {"Python", "C++", "JavaScript", "HTML"},
            {"System", "Network", "Database", "Protocol"},
            {"Port 80", "Port 21", "Port 25", "Port 443"},
            {"ENIAC", "Abacus", "Analytical Engine", "UNIVAC"},
            {"Storing data", "Processing data", "Displaying information", "All of the above"},
            {"Central Processing Unit", "Computer Processing Unit", "Central Program Unit", "Central Processor Utility"},
            {"RAM", "CPU", "Hard Disk", "Monitor"},
            {"Printer", "Mouse", "Speaker", "Monitor"},
            {"RAM", "CPU", "ROM", "Hard Disk"},
            {"Random Access Memory", "Read Access Memory", "Rapid Access Memory", "Random Active Memory"},
            {"Application software", "Operating system", "Utility software", "Driver"},
            {"To display results", "To store data", "To process instructions", "To input data"},
            {"Microsoft Word", "Linux", "Adobe Photoshop", "VLC Media Player"},
            {"General User Interface", "Graphical User Interface", "Group User Input", "Graphical User Interaction"},
            {"Oriented Object Programming", "Object Oriented Programming", "Overloading Object Programming", "Object Ore Programming"}
    };

    public static String correctAnswers[] ={
            "Cybercrime",
            "Second",
            "Vacuum tube",
            "Integrated Circuit",
            "1946",
            "Data",
            "Input - processing - output",
            "Charles babbage",
            "1642",
            "Charles Babbage",
            "Acceleration",
            "Abacus device",
            "True",
            "Herman hollerith",
            "Large scale Integrated circuit (1972 - 1987)",
            "Knowledge based system",
            "Charles Babbage",
            "Analytical Engine",
            "Mechanical",
            "Kilohertz",
            "Fourth",
            "ALU",
            "RAM",
            "System software",
            "Kilobytes",
            "Automated computer",
            "Calculator & Wrist watch",
            "Thermometer & petrol dispenser",
            "Super computers",
            "Super computer",
            "Input and output",
            "Mainframe",
            "Mini computer",
            "Computer applied in village",
            "1963",
            "Microsoft word",
            "Internet",
            "True",
            "True",
            "Hyper text transfer protocol",
            "Dynamic Host Configuration Protocol",
            "Facebook",
            "Spreadsheet",
            "Spreadsheet application",
            "Graphical user interface (GUI)",
            "Computer software",
            "Operating system",
            "Personal  Area Network",
            "Virtual Private Network",
            "CPU",
            "Random Access Memory",
            "Modem",
            "Monitor",
            "Output data",
            "ROM",
            "Hard Disk Drive (HDD)",
            "Solid State Drive",
            "CPU",
            "ROM",
            "Set of instructions to perform tasks",
            "Linux",
            "Manage hardware and software resources",
            "MS Word",
            "Graphical User Interface",
            "Compiler",
            "Hypertext Transfer Protocol",
            "Antivirus",
            "Linux",
            "Adobe Dreamweaver",
            "Bit",
            "Binary",
            "Binary",
            "Java",
            "Microcomputer",
            "Internet Protocol",
            "Vacuum Tubes",
            "Router",
            "Uniform Resource Locator",
            "Domain Name System",
            "Printer",
            "RAM",
            "C",
            "Scanner",
            "Wide Area Network",
            "Spreadsheet Software",
            "Python",
            "Network",
            "Port 80",
            "Analytical Engine",
            "All of the above",
            "Central Processing Unit",
            "CPU",
            "Mouse",
            "Hard Disk",
            "Random Access Memory",
            "Operating system",
            "To display results",
            "Linux",
            "Graphical User Interface",
            "Object Oriented Programming"
    };
};